# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 14]

    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew build

  deploy-to-tomcat:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 14]
        tomcat: [9.0.30, 8.5.30]
    env: 
      TOMCAT_VERSION: ${{ matrix.tomcat }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: wget https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_VERSION:0:1}/v${{ matrix.tomcat }}/bin/apache-tomcat-${{ matrix.tomcat }}.zip
      - run: unzip apache-tomcat-${{ matrix.tomcat }}.zip
      - run: chmod a+x apache-tomcat-${{ matrix.tomcat }}/bin/*.sh
      - run: apache-tomcat-${{ matrix.tomcat }}/bin/catalina.sh start
      - name: Build with Gradle
        run: ./gradlew bootWar
